source "https://rubygems.org"
ruby "2.4.4"
#gem "rbenv-rehash"
gem "capistrano", require: false
gem "capistrano-rbenv"
gem "capistrano-bundler"
gem "capistrano-rvm"
gem "backports"
gem "diff-lcs"
gem "multi_json"
gem "mustermann"
gem "rack-protection"
gem "sinatra"
gem "sinatra-contrib"
gem "rspec"
gem "json"
gem "tic_tac_toe_rz"
